### ISSUE TITLE
Document arg_parser in ConfigurationGathering.py, load_configuration function

### ISSUE THREAD

**Issue by Nosferatul** [coala/coala#4101]

**Comment by JohnS-01** [comment]
Let me know if I need to change anything or if I did something wrong.

**Comment by newbazz** [comment]
I would like to work on this issue if you are not working. @JohnS-01

**Comment by newbazz** [comment]
I think this issue has been fixed, can anyone reproduce it.

**Comment by JohnS-01** [comment]
You can fix it.

________________________________

**Comment by newbazz** [comment]
i think it has already been fixed.

**Comment by Makman2** [comment]
@newbazz it's not fixed ;) PR was closed before merge ;)
@JohnS-01 you really don't want to retry it? ;)

**Comment by JohnS-01** [comment]
No, I am busy right now and I still need to learn how to squash commits. So you can let someone else try or make a new ticket.

________________________________

**Comment by newbazz** [comment]
I want to work on this issue.

**Comment by newbazz** [comment]
![image](https://user-images.githubusercontent.com/25884863/31661041-fb23e2a6-b356-11e7-938b-309025fe00e5.png)
It has been documented

**Comment by Makman2** [comment]
Indeed, seems that it was fixed in the meanwhile.
